export const SEARCH_PLACES = "SEARCH_PLACES";
export const SEARCH_PLACES_SUCCESS = "SEARCH_PLACES_SUCCESS";
export const SEARCH_PLACES_ERROR = "SEARCH_PLACES_ERROR";
export const ADD_TO_SEARCH_HISTORY = "ADD_TO_SEARCH_HISTORY";
